version: "3.2"

services:
  backend:
    container_name: power-consumption-api
    image: power-consumption-api
    user: root
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        - TZ=America/Sao_Paulo
    env_file:
      - ./docker/.docker.env
    volumes:
      - type: bind
        source: ./
        target: /power-consumption
    ports:
      - target: 3000
        published: 8080
    networks:
      - power-consumption-api-network

networks:
  power-consumption-api-network:
